---
# Playbook for local server specific code

- name: check if test_results_dir variable was set by build server
  fail: msg="Variable test_results_dir was not set by CI server"
  when: test_results_dir is not defined

# Ignore errors to prevent failure in case of empty tests folder
- name: Move unit tests results
  shell: bash -c "mv -vt {{test_results_dir}} {{ros_workspace}}/build/test_results/*"
  ignore_errors: yes

- name: Print out the contents of all the failed unit test files
  script: ../files/print_errors_from_files.sh {{test_results_dir}}

- name: Fail in case if unit tests failing
  shell: bash -c "! grep -E -R '<failure|<error' {{test_results_dir}}"
