---
# Release debs
- name: Remove moveit directory
  file:
    path: {{ros_workspace}}/src/moveit
    state: absent

- name: Remove moveit with wstool
  command: wstool remove moveit
  args:
    chdir: {{ros_workspace}}/src

- name: Install moveit via apt
  apt:
    name: ros-melodic-moveit
    state: present

- name: Add base_deps repos to base
  become: yes
  shell: mv {{ros_workspace}}/../base_deps/src/* {{ros_workspace}}/src/

- name: Remove base_deps
  file:
    path: {{ros_workspace}}/../base_deps/
    state: absent

- name: Remove devel directory
  file:
    path: {{ros_workspace}}/devel
    state: absent

- name: Remove build directory
  file:
    path: {{ros_workspace}}/build
    state: absent

- name: catkin_make combined workspace
  shell: catkin_make
  args:
    chdir: {{ros_workspace}}

- include_role:
    name: check_deb_make

- name: Make debs dir for output
  file:
    path: /home/user/debs
    state: directory

- name: Copy debs to deb folder, preserving folder structure
  shell: find -name "*.deb" | xargs cp --parents -t /home/user/debs


