---
# VSCode IDE installation

- name: Update package lists
  apt: update_cache=yes
  become: yes

- name: Download VSC .deb file
  get_url:
    url: https://go.microsoft.com/fwlink/?LinkID=760868
    dest: /tmp/code.deb
  become: yes

- name: Install VSC from .deb
  apt: deb={{item}}
  become: yes
  with_items:
    - /tmp/code.deb

- name: Remove VSC .deb file
  file:
    state: absent
    path: /tmp/code.deb
  become: yes