# Install Mujoco Simulator

- name: Download Mujoco software in home
  shell: bash -c "wget "https://www.roboti.us/download/mjpro150_linux.zip" -P /home/{{ros_user}}"
  become: yes

- name: Unzip Mujoco software
  shell: bash -c "unzip /home/{{ros_user}}/mjpro150_linux.zip -d /home/{{ros_user}}"
  become: yes

- name: Install libglfw3-dev
  sudo: yes
  apt:
    name: libglfw3-dev

- name: Install libglew
  sudo: yes
  apt:
    name: libglew-dev

- name: Clone mujoco_ros_pkgs in {{workspace_path}}
  git:
    repo: 'git@github.com:shadow-robot/mujoco_ros_pkgs.git'
    version: kinetic-devel
    dest: "{{workspace_path}}/src/mujoco_ros_pkgs"
    clone: yes
    depth: 1
    update: yes

- name: Install required rosdeps
  shell: bash -c "rosdep install --from-paths . --ignore-src --rosdistro kinetic -y"
    chdir={{workspace_path}}

- name: Build the workspace
  shell: bash -c "source /opt/ros/{{ros_release}}/setup.bash && catkin_make"
    chdir={{workspace_path}}
